CREATE DATABASE IF NOT EXISTS mydb;

DROP USER IF EXISTS 'USUARIOSSUPER'@'localhost';
DROP USER IF EXISTS 'ADMINISTRADOR'@'localhost';
DROP USER IF EXISTS 'ESTUDIANTELEI'@'localhost';
DROP USER IF EXISTS 'PROFESOR'@'localhost';


CREATE USER 'USUARIOSSUPER'@'localhost' IDENTIFIED BY '2017_CaadiJuegos_*UsrSpr?!*';
CREATE USER 'ADMINISTRADOR'@'localhost' IDENTIFIED BY '2017_CaadiJuegos_*Admint?!*';
CREATE USER 'ESTUDIANTELEI'@'localhost' IDENTIFIED BY '2017_CaadiJuegos_*EstLei?!*';
CREATE USER 'PROFESOR'@'localhost'      IDENTIFIED BY '2017_CaadiJuegos_*ProfSr?!*';

GRANT INSERT, SELECT, UPDATE, DELETE ON mydb.* TO 'ADMINISTRADOR'@'localhost';
GRANT INSERT, SELECT, UPDATE ON mydb.* TO 'ESTUDIANTELEI'@'localhost';
GRANT SELECT ON mydb.* TO 'PROFESOR'@'localhost';
GRANT SELECT ON mydb.* TO 'USUARIOSSUPER'@'localhost';
